name: Daily News Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 11 * * *'

jobs:
  send-news:
    runs-on: ubuntu-latest
    steps:
      - name: Call news scheduler
        run: curl -X GET "https://doohoon-bot.onrender.com/news-scheduler.php"
